Repository samdoreee/FieldGeoLogServer, pull requests merged in 2022-12, with the labels that each got.

#12 refactor: application.properties를 yml 형식으로 변환
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: refactor

#14 test: 테스트 추가 및 API 문서화 작업
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/samdoree/fieldgeolog/Spot/DTO/SpotResponseDTO.java
  src/main/java/com/samdoree/fieldgeolog/Spot/Entity/Spot.java
  src/test/java/com/samdoree/fieldgeolog/AcceptanceTest/SpotTest.java
  src/test/java/com/samdoree/fieldgeolog/ApiDocumentUtils.java
  src/test/resources/application.properties
  src/test/resources/application.yml
Labels: documentation, test

#5 feat: 기상청 날씨 API 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/samdoree/fieldgeolog/FieldGeoLogApplication.java
  src/main/java/com/samdoree/fieldgeolog/Spot/DTO/SpotEditRequestDTO.java
  src/main/java/com/samdoree/fieldgeolog/Spot/DTO/SpotInsertRequestDTO.java
  src/main/java/com/samdoree/fieldgeolog/Spot/DTO/SpotResponseDTO.java
  src/main/java/com/samdoree/fieldgeolog/Spot/Entity/Spot.java
  src/main/java/com/samdoree/fieldgeolog/Spot/Service/SpotRegisterService.java
  src/main/java/com/samdoree/fieldgeolog/Spot/Service/WeatherApi.java
  src/main/java/com/samdoree/fieldgeolog/config/WeatherApiKey.java
  src/main/resources/application.yml
  src/test/java/com/samdoree/fieldgeolog/AcceptanceTest/SpotTest.java
  src/test/java/com/samdoree/fieldgeolog/Spot/Service/WeatherApiTest.java
  src/test/resources/application.properties
  src/test/resources/application.yml
Labels: feature

#16 feat: 메모 기능(등록, 조회, 수정, 삭제) 구현
  build.gradle
  src/main/java/com/samdoree/fieldgeolog/File/DTO/FileResponseDTO.java
  src/main/java/com/samdoree/fieldgeolog/File/Entity/File.java
  src/main/java/com/samdoree/fieldgeolog/File/Repository/FileRepository.java
  src/main/java/com/samdoree/fieldgeolog/File/Service/FileSearchService.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Controller/MemoController.java
  src/main/java/com/samdoree/fieldgeolog/Memo/DTO/MemoRequestDTO.java
  src/main/java/com/samdoree/fieldgeolog/Memo/DTO/MemoResponseDTO.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Entity/Memo.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Repository/MemoRepository.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Service/MemoModifyService.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Service/MemoRegisterService.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Service/MemoRemoveService.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Service/MemoSearchService.java
  src/main/resources/application.yml
Labels: feature

#22 test: 메모 관련 테스트 및 API 문서화 추가
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/samdoree/fieldgeolog/Memo/DTO/MemoResponseDTO.java
  src/main/java/com/samdoree/fieldgeolog/Memo/Entity/Memo.java
  src/test/java/com/samdoree/fieldgeolog/AcceptanceTest/MemoTest.java
  src/test/java/com/samdoree/fieldgeolog/AcceptanceTest/SpotTest.java
Labels: documentation, test
